[tool.poetry]
name = "agora-bridge"
version = "0.1.0"
description = "https://anagora.org/agora+bridge"
authors = ["Flancian <0@flancia.org>"]
license = "Apache2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
feedparser = "^6.0.10"
html2text = "^2020.1.16"
python-slugify = "^6.1.2"
PyYAML = "^6.0"
sgmllib3k = "^1.0.0"
text-unidecode = "^1.3"
Flask = "^2.2.2"
jsons = "^1.6.3"
mastodon-py = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
